services:
  postgres:
    image: postgres:16
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=durable_queue
      - POSTGRES_USER=durable_queue
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports: # for development
      - "25432:5432"


  sqs:
    image: softwaremill/elasticmq-native:1.6.10
    ports: # for development
      - "29324:9324"

  api:
    build: . # build context is docker-compose.yml file location
    command: sh -c "python manage.py migrate && gunicorn durable_queue.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env # load .env at runtime, not COPY into image
    environment:
      - CELERY_BROKER_URL=sqs://x:x@sqs:9324
      - POSTGRES_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
      sqs:
        condition: service_started

  worker:
    build: .
    command: celery -A durable_queue worker -l info
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=sqs://x:x@sqs:9324
      - POSTGRES_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
      sqs:
        condition: service_started

volumes:
  pgdata:
