# Generated by Django 6.0.6 on 2026-07-01 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptionjob',
            name='attempt_count',
        ),
    ]
