# Generated by Django 6.0.6 on 2026-07-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_socialidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionjob',
            name='worker_attempts',
            field=models.JSONField(default=list),
        ),
    ]
