# Generated by Django 6.0.6 on 2026-07-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_transcriptionjob_attempt_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptionjob',
            name='claimed_at',
        ),
    ]
