# Generated by Django 6.0.6 on 2026-09-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_transcriptionjob_worker_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionjob',
            name='worker_attempts_before_retry',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
